services:
  check-redirects:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8090"
    environment:
      SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
      CACHE_URLS: ${CACHE_URLS}
    # Use resolvers without content filtering for redirect targets.
    dns:
      - 1.1.1.1
      - 8.8.8.8
