version: '3'

dotenv:
  - .env

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  prod:
    desc: Run the embedded server with UI and PB together with prod
    env:
      NODE_ENV: production
    cmds:
      - |
        air -build.pre_cmd="cd ui/ && pnpm run build" \
        -build.args_bin="--dir=$(pwd)/pb_data \
        --dev=true serve {{.CLI_ARGS}}"
  dev:
    desc: Run the embedded server with UI and PB together
    env:
      NODE_ENV: development
    cmds:
      - |
        air -build.pre_cmd="cd ui/ && pnpm run build" \
        -build.args_bin="--dir=$(pwd)/pb_data \
        --dev=true serve {{.CLI_ARGS}}"
  api:
    desc: Run the server with hot reload and pass through any additional args
    summary: Use this to run the serve isolated, typically when also running UI IDE
    cmds:
      - | 
        air -build.args_bin="--dir=$(pwd)/pb_data \
        --dev=true serve {{.CLI_ARGS}}"
    silent: true
  ui:
    desc: Run the UI
    summary: Use this to run the UI isolated, typically when also running server
    dir: ./ui
    cmds:
      - pnpm run dev

  ui:lint:
    desc: Run linting on the UI
    dir: ./ui
    cmds:
      - pnpm run prettier

  audit:
    desc: Run audit on the UI and Backend
    cmds:
      - task: ui:lint
      - betteralign -apply ./...
      - task: golines
      - golangci-lint run ./... {{.CLI_ARGS}}


  golines:
    desc: run golines . -w
    cmds:
      - golines . -w --no-reformat-tags --ignore-generated {{.CLI_ARGS}}

