/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'

const IndexLazyRouteImport = createFileRoute('/')()
const CodesLazyRouteImport = createFileRoute('/codes')()
const CodesCodeIdLazyRouteImport = createFileRoute('/codes_/$codeId')()
const ResultsResultIdLazyRouteImport = createFileRoute('/results_/$resultId')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesLazyRoute = CodesLazyRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/codes.lazy').then((d) => d.Route))
const CodesCodeIdLazyRoute = CodesCodeIdLazyRouteImport.update({
  id: '/codes_/$codeId',
  path: '/codes/$codeId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/codes_.$codeId.lazy').then((d) => d.Route),
)
const ResultsResultIdLazyRoute = ResultsResultIdLazyRouteImport.update({
  id: '/results_/$resultId',
  path: '/results/$resultId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/results_.$resultId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/codes': typeof CodesLazyRoute
  '/codes/$codeId': typeof CodesCodeIdLazyRoute
  '/results/$resultId': typeof ResultsResultIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/codes': typeof CodesLazyRoute
  '/codes/$codeId': typeof CodesCodeIdLazyRoute
  '/results/$resultId': typeof ResultsResultIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRoute
  '/codes': typeof CodesLazyRoute
  '/codes_/$codeId': typeof CodesCodeIdLazyRoute
  '/results_/$resultId': typeof ResultsResultIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/codes' | '/codes/$codeId' | '/results/$resultId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/codes' | '/codes/$codeId' | '/results/$resultId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/codes'
    | '/codes_/$codeId'
    | '/results_/$resultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutRoute: typeof AboutRoute
  CodesLazyRoute: typeof CodesLazyRoute
  CodesCodeIdLazyRoute: typeof CodesCodeIdLazyRoute
  ResultsResultIdLazyRoute: typeof ResultsResultIdLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes_/$codeId': {
      id: '/codes_/$codeId'
      path: '/codes/$codeId'
      fullPath: '/codes/$codeId'
      preLoaderRoute: typeof CodesCodeIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results_/$resultId': {
      id: '/results_/$resultId'
      path: '/results/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof ResultsResultIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutRoute: AboutRoute,
  CodesLazyRoute: CodesLazyRoute,
  CodesCodeIdLazyRoute: CodesCodeIdLazyRoute,
  ResultsResultIdLazyRoute: ResultsResultIdLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
